from typing import Protocol

from app.models.document import DocumentModel
from app.models.finding import FindingModel
from app.models.session import SessionModel, TranscriptEntryModel
from app.models.workspace import WorkspaceModel


class WorkspaceRepository(Protocol):
    async def list_all(self) -> list[WorkspaceModel]: ...
    async def get_by_id(self, workspace_id: str) -> WorkspaceModel | None: ...
    async def create(self, workspace: WorkspaceModel) -> WorkspaceModel: ...
    async def update(self, workspace: WorkspaceModel) -> WorkspaceModel: ...
    async def delete(self, workspace_id: str) -> None: ...


class DocumentRepository(Protocol):
    async def list_by_workspace(self, workspace_id: str) -> list[DocumentModel]: ...
    async def get_by_id(self, doc_id: str) -> DocumentModel | None: ...
    async def create(self, document: DocumentModel) -> DocumentModel: ...
    async def update(self, document: DocumentModel) -> DocumentModel: ...
    async def delete(self, doc_id: str) -> None: ...


class SessionRepository(Protocol):
    async def list_by_workspace(self, workspace_id: str) -> list[SessionModel]: ...
    async def list_recent(self, limit: int = 3) -> list[SessionModel]: ...
    async def get_by_id(self, session_id: str) -> SessionModel | None: ...
    async def create(self, session: SessionModel) -> SessionModel: ...
    async def get_transcript(self, session_id: str) -> list[TranscriptEntryModel]: ...
    async def add_transcript_entry(self, session_id: str, entry: TranscriptEntryModel) -> None: ...


class FindingRepository(Protocol):
    async def list_by_workspace(self, workspace_id: str) -> list[FindingModel]: ...
    async def create(self, finding: FindingModel) -> FindingModel: ...
