import type {
  Workspace,
  Document,
  ExtractedField,
  Session,
  TranscriptEntry,
  WorkspaceStats,
} from "@/types/workspace";
import type { Finding } from "@/types/finding";
import type { SuggestedQuestion } from "@/types/voice";

export const MOCK_STATS: WorkspaceStats = {
  totalWorkspaces: 3,
  totalSessions: 12,
  totalMinutesUsed: 47,
};

export const MOCK_WORKSPACES: Workspace[] = [
  {
    id: "ws-001",
    name: "Insurance Claims — AUT-2024-789",
    domain: "insurance_claims",
    status: "active",
    documentCount: 4,
    sessionCount: 5,
    findingCount: 3,
    phoneNumber: "+1 (555) 234-5678",
    lastCallAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    minutesUsed: 23,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "ws-002",
    name: "Legal Review — Acme NDA",
    domain: "legal_contracts",
    status: "active",
    documentCount: 2,
    sessionCount: 3,
    findingCount: 1,
    phoneNumber: null,
    lastCallAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    minutesUsed: 15,
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "ws-003",
    name: "Financial DD — Series B",
    domain: "financial_dd",
    status: "setup",
    documentCount: 6,
    sessionCount: 4,
    findingCount: 5,
    phoneNumber: "+1 (555) 987-6543",
    lastCallAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    minutesUsed: 9,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_EXTRACTED_FIELDS: ExtractedField[] = [
  {
    key: "policy_number",
    value: "AUT-2024-789",
    source: "Policy-AUT-789.pdf",
    confidence: 0.99,
    isAnomaly: false,
    anomalyReason: null,
  },
  {
    key: "claimant_name",
    value: "John Smith",
    source: "FNOL-2024-1234.pdf",
    confidence: 0.97,
    isAnomaly: false,
    anomalyReason: null,
  },
  {
    key: "date_of_loss",
    value: "2024-03-16",
    source: "FNOL-2024-1234.pdf",
    confidence: 0.95,
    isAnomaly: false,
    anomalyReason: null,
  },
  {
    key: "bi_limit",
    value: "100000",
    source: "Policy-AUT-789.pdf",
    confidence: 0.98,
    isAnomaly: false,
    anomalyReason: null,
  },
  {
    key: "pd_limit",
    value: "50000",
    source: "Policy-AUT-789.pdf",
    confidence: 0.98,
    isAnomaly: false,
    anomalyReason: null,
  },
  {
    key: "deductible",
    value: "1000",
    source: "Policy-AUT-789.pdf",
    confidence: 0.99,
    isAnomaly: false,
    anomalyReason: null,
  },
  {
    key: "passengers_fnol",
    value: "2",
    source: "FNOL-2024-1234.pdf",
    confidence: 0.92,
    isAnomaly: true,
    anomalyReason: "Police report lists 3 passengers — discrepancy detected",
  },
  {
    key: "passengers_police",
    value: "3",
    source: "Police-Report-2024.pdf",
    confidence: 0.96,
    isAnomaly: true,
    anomalyReason: "FNOL lists 2 passengers — discrepancy detected",
  },
  {
    key: "total_medical",
    value: "47250",
    source: "Medical-Bills-Combined.pdf",
    confidence: 0.94,
    isAnomaly: true,
    anomalyReason: "Medical bills ($47,250) approach 50% of BI limit ($100,000)",
  },
  {
    key: "vehicle_year",
    value: "2022",
    source: "FNOL-2024-1234.pdf",
    confidence: 0.97,
    isAnomaly: false,
    anomalyReason: null,
  },
  {
    key: "vehicle_make",
    value: "Toyota Camry",
    source: "FNOL-2024-1234.pdf",
    confidence: 0.96,
    isAnomaly: false,
    anomalyReason: null,
  },
  {
    key: "loss_location",
    value: "Interstate 95, Mile Marker 142",
    source: "Police-Report-2024.pdf",
    confidence: 0.93,
    isAnomaly: false,
    anomalyReason: null,
  },
  {
    key: "weather_conditions",
    value: "Clear",
    source: "Police-Report-2024.pdf",
    confidence: 0.91,
    isAnomaly: false,
    anomalyReason: null,
  },
  {
    key: "er_visit_date",
    value: "2024-03-16",
    source: "Medical-Bills-Combined.pdf",
    confidence: 0.95,
    isAnomaly: false,
    anomalyReason: null,
  },
  {
    key: "treatment_provider",
    value: "Mercy General Hospital",
    source: "Medical-Bills-Combined.pdf",
    confidence: 0.94,
    isAnomaly: false,
    anomalyReason: null,
  },
];

export const MOCK_DOCUMENTS: Document[] = [
  {
    id: "doc-001",
    workspaceId: "ws-001",
    filename: "FNOL-2024-1234.pdf",
    documentType: "fnol",
    status: "ready",
    s3Key: "ws-001/documents/fnol-2024-1234.pdf",
    sizeBytes: 245_000,
    sizeTokens: 3200,
    extractedFields: MOCK_EXTRACTED_FIELDS.filter(
      (f) => f.source === "FNOL-2024-1234.pdf"
    ),
    processingError: null,
    isReferenced: false,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "doc-002",
    workspaceId: "ws-001",
    filename: "Policy-AUT-789.pdf",
    documentType: "policy",
    status: "ready",
    s3Key: "ws-001/documents/policy-aut-789.pdf",
    sizeBytes: 520_000,
    sizeTokens: 4800,
    extractedFields: MOCK_EXTRACTED_FIELDS.filter(
      (f) => f.source === "Policy-AUT-789.pdf"
    ),
    processingError: null,
    isReferenced: true,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "doc-003",
    workspaceId: "ws-001",
    filename: "Medical-Bills-Combined.pdf",
    documentType: "medical_bill",
    status: "ready",
    s3Key: "ws-001/documents/medical-bills-combined.pdf",
    sizeBytes: 380_000,
    sizeTokens: 2100,
    extractedFields: MOCK_EXTRACTED_FIELDS.filter(
      (f) => f.source === "Medical-Bills-Combined.pdf"
    ),
    processingError: null,
    isReferenced: false,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "doc-004",
    workspaceId: "ws-001",
    filename: "Police-Report-2024.pdf",
    documentType: "police_report",
    status: "ready",
    s3Key: "ws-001/documents/police-report-2024.pdf",
    sizeBytes: 290_000,
    sizeTokens: 1800,
    extractedFields: MOCK_EXTRACTED_FIELDS.filter(
      (f) => f.source === "Police-Report-2024.pdf"
    ),
    processingError: null,
    isReferenced: false,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_SESSIONS: Session[] = [
  {
    id: "sess-001",
    workspaceId: "ws-001",
    channel: "web",
    callerId: null,
    startedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    endedAt: new Date(
      Date.now() - 2 * 60 * 60 * 1000 + 8 * 60 * 1000
    ).toISOString(),
    durationSeconds: 480,
    findingCount: 3,
    transcriptUrl: null,
  },
  {
    id: "sess-002",
    workspaceId: "ws-001",
    channel: "phone",
    callerId: "+1 (555) 111-2222",
    startedAt: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
    endedAt: new Date(
      Date.now() - 26 * 60 * 60 * 1000 + 12 * 60 * 1000
    ).toISOString(),
    durationSeconds: 720,
    findingCount: 1,
    transcriptUrl: null,
  },
  {
    id: "sess-003",
    workspaceId: "ws-001",
    channel: "web",
    callerId: null,
    startedAt: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    endedAt: new Date(
      Date.now() - 72 * 60 * 60 * 1000 + 5 * 60 * 1000
    ).toISOString(),
    durationSeconds: 300,
    findingCount: 0,
    transcriptUrl: null,
  },
];

export const MOCK_TRANSCRIPT: TranscriptEntry[] = [
  {
    id: "t-001",
    role: "agent",
    text: "Hello! I'm your DocuVoice assistant for the Insurance Claims workspace AUT-2024-789. I have 4 documents loaded. How can I help you today?",
    timestamp: 0,
    documentRef: null,
    toolCall: null,
  },
  {
    id: "t-002",
    role: "user",
    text: "Can you summarize the key details from the First Notice of Loss?",
    timestamp: 5,
    documentRef: null,
    toolCall: null,
  },
  {
    id: "t-003",
    role: "agent",
    text: "Looking at the FNOL document now.",
    timestamp: 8,
    documentRef: "FNOL-2024-1234.pdf",
    toolCall: null,
  },
  {
    id: "t-004",
    role: "agent",
    text: "The First Notice of Loss was filed on March 16, 2024 by John Smith. The incident occurred on Interstate 95 at Mile Marker 142 involving a 2022 Toyota Camry. Two passengers were reported in the vehicle. The claimant reports rear-end collision during heavy traffic conditions.",
    timestamp: 12,
    documentRef: "FNOL-2024-1234.pdf",
    toolCall: null,
  },
  {
    id: "t-005",
    role: "user",
    text: "Are there any discrepancies between the FNOL and the police report?",
    timestamp: 25,
    documentRef: null,
    toolCall: null,
  },
  {
    id: "t-006",
    role: "agent",
    text: "Let me compare the fields between both documents.",
    timestamp: 28,
    documentRef: null,
    toolCall: "compare_fields()",
  },
  {
    id: "t-007",
    role: "agent",
    text: "I found a discrepancy. The FNOL reports 2 passengers, but the police report lists 3 passengers. This is a significant difference that should be investigated. Also, the weather condition is listed as 'Clear' in the police report, while the claimant mentions 'heavy traffic conditions' which may warrant further review.",
    timestamp: 35,
    documentRef: "Police-Report-2024.pdf",
    toolCall: null,
  },
  {
    id: "t-008",
    role: "user",
    text: "What about the medical bills? How do they compare to the policy limits?",
    timestamp: 50,
    documentRef: null,
    toolCall: null,
  },
  {
    id: "t-009",
    role: "agent",
    text: "Checking the medical bills against the policy coverage.",
    timestamp: 53,
    documentRef: null,
    toolCall: "compare_fields()",
  },
  {
    id: "t-010",
    role: "agent",
    text: "The combined medical bills total $47,250 from Mercy General Hospital. The policy's Bodily Injury limit is $100,000. The medical expenses are currently at 47.25% of the BI limit. This is approaching the 50% threshold that typically triggers enhanced review. The deductible is $1,000.",
    timestamp: 60,
    documentRef: "Medical-Bills-Combined.pdf",
    toolCall: null,
  },
];

export const MOCK_FINDINGS: Finding[] = [
  {
    id: "find-001",
    sessionId: "sess-001",
    workspaceId: "ws-001",
    type: "discrepancy",
    severity: "critical",
    title: "Passenger Count Mismatch",
    description:
      "The FNOL reports 2 passengers in the vehicle, but the police report documents 3 passengers. This discrepancy may indicate incomplete initial reporting or potential fraud. Recommend contacting the claimant for clarification.",
    documentRefs: ["FNOL-2024-1234.pdf", "Police-Report-2024.pdf"],
    fieldRefs: ["passengers_fnol", "passengers_police"],
    confidence: 0.94,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "find-002",
    sessionId: "sess-001",
    workspaceId: "ws-001",
    type: "exposure",
    severity: "medium",
    title: "Medical Bills Approaching BI Limit",
    description:
      "Combined medical expenses ($47,250) are at 47.25% of the Bodily Injury limit ($100,000). If additional treatment is required, this claim may exceed policy coverage. Consider early reserve adjustment.",
    documentRefs: ["Medical-Bills-Combined.pdf", "Policy-AUT-789.pdf"],
    fieldRefs: ["total_medical", "bi_limit"],
    confidence: 0.91,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "find-003",
    sessionId: "sess-001",
    workspaceId: "ws-001",
    type: "anomaly",
    severity: "low",
    title: "Weather Condition Inconsistency",
    description:
      "The police report documents weather conditions as 'Clear', while the claimant's FNOL description mentions 'heavy traffic conditions'. While traffic and weather are different factors, the narrative may benefit from additional context.",
    documentRefs: ["FNOL-2024-1234.pdf", "Police-Report-2024.pdf"],
    fieldRefs: ["weather_conditions"],
    confidence: 0.72,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_SUGGESTED_QUESTIONS: SuggestedQuestion[] = [
  {
    id: "sq-001",
    text: "Summarize all findings for this claim",
    category: "summary",
  },
  {
    id: "sq-002",
    text: "Compare FNOL details with police report",
    category: "comparison",
  },
  {
    id: "sq-003",
    text: "What are the policy coverage limits?",
    category: "analysis",
  },
  {
    id: "sq-004",
    text: "Are there any red flags in the medical bills?",
    category: "analysis",
  },
  {
    id: "sq-005",
    text: "Generate adjuster notes for this claim",
    category: "general",
  },
  {
    id: "sq-006",
    text: "What additional documents should I request?",
    category: "general",
  },
];
